---
sidebar: sidebar 
permalink: faq.html 
keywords: community, forums, help, support, videos, faq, getting help, permissions, access control lists, acls, preserve, preserving, troubleshooting, support, encryption, smb 
summary: Cloud Sync에 대한 도움말을 얻고 포럼, 채팅 서비스, 비디오 등 다양한 리소스를 통해 자세한 정보를 찾을 수 있습니다. 
---
= Cloud Sync 기술 FAQ
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다.



== 시작하기

다음 질문은 Cloud Sync를 시작하는 것과 관련이 있습니다.



=== Cloud Sync의 작동 방식

Cloud Sync는 NetApp 데이터 브로커 소프트웨어를 사용하여 소스 데이터를 타겟(이것을 _sync 관계 _ 라고 함)으로 동기화합니다.

데이터 브로커 그룹은 소스와 타겟 간의 동기화 관계를 제어합니다. 동기화 관계를 설정한 후 Cloud Sync는 소스 시스템을 분석하고 이를 여러 복제 스트림으로 분해하여 선택한 타겟 데이터를 푸시합니다.

초기 복사 후 서비스는 사용자가 설정한 일정에 따라 변경된 데이터를 동기화합니다.



=== 14일 무료 평가판은 어떻게 작동합니까?

14일 무료 평가판은 Cloud Sync 서비스에 등록할 때 시작됩니다. 14일 동안 생성한 Cloud Sync 관계에는 NetApp 비용이 적용되지 않습니다. 하지만 구축하는 데이터 브로커에 대한 모든 리소스 비용이 계속 적용됩니다.



=== Cloud Sync 비용은 얼마입니까?

Cloud Sync 사용과 관련된 비용에는 서비스 요금과 리소스 요금이라는 두 가지 유형이 있습니다.

* 서비스 요금 *

용량제 가격으로, 생성한 동기화 관계 수를 기준으로 Cloud Sync 서비스 요금은 시간당 부과됩니다.

* https://aws.amazon.com/marketplace/pp/B01LZV5DUJ["AWS에서 용량제 가격 보기"^]
* https://aws.amazon.com/marketplace/pp/B06XX5V3M2["AWS에서 연간 가격 보기"^]
* https://azuremarketplace.microsoft.com/en-us/marketplace/apps/netapp.cloud-sync-service?tab=PlansAndPrice["Azure에서 가격을 확인할 수 있습니다"^]


Cloud Sync 라이센스는 NetApp 담당자를 통해서도 제공됩니다. 각 라이센스로 12개월간 20개의 동기화 관계를 사용할 수 있습니다.

link:concept-licensing.html["라이센스에 대해 자세히 알아보십시오"].


NOTE: Cloud Sync 관계는 Cloud Volumes Service 및 Azure NetApp Files에서 무료로 제공됩니다.

* 리소스 비용 *

리소스 요금은 클라우드에서 데이터 브로커를 실행하는 데 필요한 컴퓨팅 및 스토리지 비용과 관련이 있습니다.



=== Cloud Sync는 어떻게 청구됩니까?

14일 무료 평가판이 종료된 후 동기화 관계에 대한 비용을 지불할 수 있는 두 가지 방법이 있습니다. 첫 번째 옵션은 AWS 또는 Azure에서 가입하는 것입니다. 가입 시 사용한 만큼만 지불하거나 연간 비용을 지불할 수 있습니다. 두 번째 옵션은 NetApp에서 직접 라이센스를 구매하는 것입니다.



=== 클라우드 외부에서 Cloud Sync를 사용할 수 있습니까?

예, 비클라우드 아키텍처에서 Cloud Sync를 사용할 수 있습니다. 소스와 타겟이 사내에 있을 수 있으므로 데이터 브로커 소프트웨어도 사용할 수 있습니다.

클라우드 외부에서 Cloud Sync를 사용하는 방법은 다음과 같습니다.

* 사내 동기화의 경우 NetApp StorageGRID를 통해 프라이빗 Amazon S3 버킷을 사용할 수 있습니다.
* 데이터 브로커 그룹은 Cloud Sync 서비스와 통신하기 위해 인터넷 연결이 필요합니다.
* NetApp에서 직접 라이센스를 구입하지 않을 경우 PAYGO Cloud Sync 서비스 청구를 위해 AWS 또는 Azure 계정이 필요합니다.




== 데이터 브로커 그룹이란 무엇입니까?

각 데이터 브로커는 데이터 브로커 그룹에 속해 있습니다. 데이터 브로커를 함께 그룹화하면 동기화 관계의 성능을 향상시킬 수 있습니다.



=== Cloud Sync에 어떻게 액세스합니까?

Cloud Sync는 Cloud Manager의 * 동기화 * 탭에서 사용할 수 있습니다.



== 지원되는 소스 및 타겟

동기화 관계에서 지원되는 소스 및 타겟과 관련된 다음 질문



=== Cloud Sync가 지원하는 소스와 대상은 무엇입니까?

Cloud Sync는 다양한 유형의 동기화 관계를 지원합니다. link:reference-supported-relationships.html["전체 목록을 봅니다"].



=== Cloud Sync는 어떤 버전의 NFS 및 SMB를 지원합니까?

Cloud Sync는 NFS 버전 3 이상과 SMB 버전 1 이상을 지원합니다.

link:reference-requirements.html["동기화 요구 사항에 대해 자세히 알아보십시오"].



=== Amazon S3가 타겟일 때 데이터는 특정 S3 스토리지 클래스로 계층화할 수 있습니까?

예. AWS S3가 타겟인 경우 특정 S3 스토리지 클래스를 선택할 수 있습니다.

* 표준(기본 클래스)
* 지능형 계층화
* 표준 - 낮은 액세스 빈도
* 단일 영역 - 낮은 액세스 빈도
* 빙하
* Glacier 딥 아카이브




=== Azure Blob 스토리지의 스토리지 계층에는 어떻습니까?

Blob 컨테이너가 타겟인 경우 특정 Azure Blob 저장소 계층을 선택할 수 있습니다.

* 핫 스토리지
* 멋진 보관




=== Google Cloud 스토리지 계층을 지원합니까?

예, Google Cloud Storage 버킷이 타겟인 경우 특정 스토리지 클래스를 선택할 수 있습니다.

* 표준
* 니어라인
* 콜드라인
* 아카이브




== 네트워킹

다음 질문은 Cloud Sync의 네트워킹 요구 사항과 관련이 있습니다.



=== Cloud Sync의 네트워킹 요구 사항은 무엇입니까?

Cloud Sync 환경에서는 데이터 브로커 그룹이 선택한 프로토콜 또는 오브젝트 스토리지 API(Amazon S3, Azure Blob, IBM 클라우드 오브젝트 스토리지)를 통해 소스 및 타겟에 연결되어 있어야 합니다.

또한 데이터 브로커 그룹은 포트 443을 통해 아웃바운드 인터넷 연결을 필요로 하므로 Cloud Sync 서비스와 통신하고 몇 가지 다른 서비스 및 리포지토리에 연결할 수 있습니다.

자세한 내용을 보려면 link:reference-networking.html["네트워킹 요구 사항을 검토합니다"].



=== 데이터 브로커와 함께 프록시 서버를 사용할 수 있습니까?

예.

Cloud Sync는 기본 인증을 사용하거나 사용하지 않는 프록시 서버를 지원합니다. 데이터 브로커를 배포할 때 프록시 서버를 지정하면 데이터 브로커의 모든 HTTP 및 HTTPS 트래픽이 프록시를 통해 라우팅됩니다. NFS 또는 SMB와 같은 비 HTTP 트래픽은 프록시 서버를 통해 라우팅할 수 없습니다.

프록시 서버의 유일한 제한 사항은 NFS 또는 Azure NetApp Files 동기화 관계를 사용하여 전송 중 데이터 암호화를 사용하는 것입니다. 암호화된 데이터는 HTTPS를 통해 전송되며 프록시 서버를 통해 라우팅할 수 없습니다.



== 데이터 동기화

다음 질문은 데이터 동기화 작동 방식과 관련이 있습니다.



=== 동기화가 얼마나 자주 발생합니까?

기본 스케줄은 일별 동기화에 대해 설정됩니다. 초기 동기화 후 다음을 수행할 수 있습니다.

* 원하는 일 수, 시간 또는 분으로 동기화 일정을 수정합니다
* 동기화 일정을 비활성화합니다
* 동기화 일정 삭제(데이터가 손실되지 않음. 동기화 관계만 제거됨)




=== 최소 동기화 일정은 무엇입니까?

1분마다 데이터를 동기화하도록 관계를 예약할 수 있습니다.



=== 데이터 브로커 그룹이 파일 동기화 실패 시 재시도합니까? 아니면 시간 초과입니까?

데이터 브로커 그룹은 단일 파일이 전송되지 않을 때 시간 초과되지 않습니다. 대신 데이터 브로커 그룹은 파일을 건너뛰기 전에 3번 재시도합니다. 재시도 값은 동기화 관계에 대한 설정에서 구성할 수 있습니다.

link:task-managing-relationships.html#changing-the-settings-for-a-sync-relationship["동기화 관계의 설정을 변경하는 방법에 대해 알아봅니다"].



=== 매우 큰 데이터 세트가 있는 경우 어떻게 해야 합니까?

단일 디렉토리에 600,000개 이상의 파일이 있는 경우 페이로드를 처리하도록 데이터 브로커 그룹을 구성할 수 있도록 mailto:ng-cloudsync-support@netapp.com [contact us] 를 사용합니다. 데이터 브로커 그룹에 메모리를 추가해야 할 수도 있습니다.

마운트 지점의 총 파일 수에는 제한이 없습니다. 계층 구조(최상위 디렉토리 또는 하위 디렉토리)의 레벨에 관계없이 60만 개 이상의 파일이 있는 대규모 디렉토리에 대해서는 추가 메모리가 필요합니다.



== 보안

보안과 관련된 다음 질문입니다.



=== Cloud Sync는 안전합니까?

예. 모든 Cloud Sync 서비스 네트워킹 연결은 을 사용하여 수행됩니다 https://aws.amazon.com/sqs/["아마존 단순 대기열 서비스(SQS)"^].

데이터 브로커 그룹과 Amazon S3, Azure Blob, Google Cloud Storage 및 IBM Cloud Object Storage 간의 모든 통신은 HTTPS 프로토콜을 통해 수행됩니다.

사내(소스 또는 타겟) 시스템에서 Cloud Sync를 사용하는 경우 다음과 같은 몇 가지 권장 연결 옵션을 활용할 수 있습니다.

* 인터넷에 연결되지 않은 AWS Direct Connect, Azure ExpressRoute 또는 Google Cloud Interconnect 연결(지정한 클라우드 네트워크와만 통신할 수 있음)
* 온-프레미스 게이트웨이 장치와 클라우드 네트워크 간의 VPN 연결
* S3 버킷, Azure Blob 스토리지 또는 Google Cloud Storage를 통한 추가 보안 데이터 전송을 위해 Amazon Private S3 Endpoint, Azure Virtual Network 서비스 끝점 또는 Private Google Access를 설정할 수 있습니다.


이러한 방법 중 하나라도 있으면 사내 NAS 서버와 Cloud Sync 데이터 브로커 그룹 간에 보안 연결이 설정됩니다.



=== Cloud Sync에서 데이터를 암호화합니까?

* Cloud Sync는 소스 및 타겟 NFS 서버 간에 전송 중 데이터 암호화를 지원합니다. link:task-nfs-encryption.html["자세한 정보"].
* SMB의 경우 Cloud Sync는 서버 측에서 암호화한 SMB 3.0 및 3.11 데이터를 지원합니다. Cloud Sync는 암호화된 데이터를 소스에서 데이터가 암호화된 상태로 유지되는 타겟으로 복사합니다.
+
Cloud Sync는 SMB 데이터 자체를 암호화할 수 없습니다.

* Amazon S3 버킷이 동기화 관계의 타겟인 경우 AWS KMS 암호화 또는 AES-256 암호화를 사용하여 데이터 암호화를 사용할지 여부를 선택할 수 있습니다.




== 권한

다음 질문은 데이터 권한과 관련이 있습니다.



=== SMB 데이터 권한이 타겟 위치에 동기화됩니까?

소스 SMB 공유와 타겟 SMB 공유 간, 소스 SMB 공유에서 오브젝트 스토리지(ONTAP S3 제외) 간에 액세스 제어 목록(ACL)을 보존하도록 Cloud Sync을 설정할 수 있습니다.


NOTE: Cloud Sync는 오브젝트 스토리지에서 SMB 공유로의 ACL 복제를 지원하지 않습니다.

link:task-copying-acls.html["SMB 공유 간에 ACL을 복사하는 방법에 대해 알아봅니다"].



=== NFS 데이터 권한이 타겟 위치에 동기화됩니까?

Cloud Sync는 다음과 같이 NFS 서버 간에 NFS 권한을 자동으로 복제합니다.

* NFS 버전 3: Cloud Sync는 사용 권한과 사용자 그룹 소유자를 복사합니다.
* NFS 버전 4: Cloud Sync는 ACL을 복제합니다.




== 오브젝트 스토리지 메타데이터

Cloud Sync는 다음과 같은 유형의 동기화 관계를 위해 소스에서 타겟으로 오브젝트 스토리지 메타데이터를 복제합니다.

* Amazon S3 -> Amazon S3 ^1^
* Amazon S3 -> StorageGRID 를 선택합니다
* StorageGRID -> Amazon S3
* StorageGRID -> StorageGRID
* StorageGRID -> Google 클라우드 스토리지
* Google 클라우드 스토리지 -> StorageGRID^1^
* Google Cloud Storage -> IBM Cloud Object Storage ^1^
* Google Cloud Storage -> Amazon S3 ^1^
* Amazon S3 -> Google Cloud Storage 를 클릭합니다
* IBM Cloud Object Storage -> Google Cloud Storage
* StorageGRID -> IBM 클라우드 오브젝트 스토리지
* IBM 클라우드 오브젝트 스토리지 -> StorageGRID
* IBM 클라우드 오브젝트 스토리지 -> IBM 클라우드 오브젝트 스토리지


^1^ 이러한 동기화 관계의 경우 해야 합니다 link:task-creating-relationships.html["동기화 관계를 생성할 때 설정을 활성화합니다"].



== 성능

다음 질문은 Cloud Sync 성능과 관련이 있습니다.



=== 동기화 관계의 진행률 표시기는 무엇을 나타냅니까?

동기화 관계는 데이터 브로커 그룹의 네트워크 어댑터의 처리량을 보여 줍니다. 여러 데이터 브로커를 사용하여 동기화 성능을 가속화하면 처리량은 모든 트래픽의 합계입니다. 이 처리량은 20초마다 새로 고쳐집니다.



=== 성능 문제가 발생했습니다. 동시 전송 수를 제한할 수 있습니까?

용량이 매우 큰 파일(각 BB가 여러 개 있는 경우)이 있으면 전송 프로세스를 완료하는 데 시간이 오래 걸릴 수 있으며 성능에 영향을 줄 수 있습니다.

동시 전송 수를 제한하는 것은 도움이 될 수 있습니다. mailto:ng-cloudsync-support@netapp.com [문의처].



=== Azure NetApp Files에서 성능이 낮은 이유는 무엇입니까?

Azure NetApp Files 간에 데이터를 동기화할 때 디스크 서비스 수준이 Standard인 경우 장애 및 성능 문제가 발생할 수 있습니다.

동기화 성능을 향상시키려면 서비스 수준을 Premium 또는 Ultra로 변경합니다.

https://docs.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-service-levels#throughput-limits["Azure NetApp Files 서비스 수준 및 처리량 에 대해 자세히 알아보십시오"^].



=== AWS용 Cloud Volumes Service의 성능이 낮은 이유는 무엇입니까?

클라우드 볼륨과 데이터를 동기화할 때 클라우드 볼륨의 성능 수준이 Standard인 경우 장애 및 성능 문제가 발생할 수 있습니다.

동기화 성능을 향상시키려면 서비스 수준을 Premium 또는 Extreme으로 변경하십시오.



=== 그룹에 필요한 데이터 브로커는 몇 개입니까?

새 관계를 만들 때는 가속화된 동기화 관계에 속하는 기존 데이터 브로커를 선택하지 않는 한 그룹의 단일 데이터 브로커로 시작합니다. 대부분의 경우 단일 데이터 브로커가 동기화 관계에 대한 성능 요구사항을 충족할 수 있습니다. 그렇지 않으면 그룹에 추가 데이터 브로커를 추가하여 동기화 성능을 가속화할 수 있습니다. 하지만 먼저 동기화 성능에 영향을 줄 수 있는 다른 요소를 확인해야 합니다.

여러 요소가 데이터 전송 성능에 영향을 줄 수 있습니다. 네트워크 대역폭, 지연 시간, 네트워크 토폴로지, 데이터 브로커 VM 사양 및 스토리지 시스템 성능 때문에 전반적인 동기화 성능이 영향을 받을 수 있습니다. 예를 들어, 그룹의 단일 데이터 브로커는 100MB/s에 도달할 수 있지만 타겟의 디스크 처리량은 64MB/s만 허용할 수 있습니다 따라서 데이터 브로커 그룹은 데이터를 복사하려고 계속 노력하고 있지만 타겟 고객은 데이터 브로커 그룹의 성능을 충족할 수 없습니다.

따라서 대상의 네트워킹 성능과 디스크 처리량을 확인해야 합니다.

그런 다음 그룹에 추가 데이터 브로커를 추가하여 해당 관계의 로드를 공유함으로써 동기화 성능을 높일 수 있습니다. link:task-managing-relationships.html#accelerating-sync-performance["동기화 성능을 가속화하는 방법에 대해 알아보십시오"].



== 항목을 삭제하는 중입니다

다음 질문은 원본 및 대상에서 동기화 관계 및 데이터를 삭제하는 것과 관련이 있습니다.



=== Cloud Sync 관계를 삭제하면 어떻게 됩니까?

관계를 삭제하면 이후의 모든 데이터 동기화가 중지되고 결제가 종료됩니다. 대상에 동기화된 데이터는 그대로 유지됩니다.



=== 소스 서버에서 항목을 삭제하면 어떻게 됩니까? 대상에서도 제거됩니까?

기본적으로 활성 동기화 관계가 있는 경우 소스 서버에서 삭제된 항목은 다음 동기화 중에 대상에서 삭제되지 않습니다. 그러나 각 관계의 동기화 설정에는 Cloud Sync가 소스에서 삭제된 경우 대상 위치의 파일을 삭제하도록 정의할 수 있는 옵션이 있습니다.

link:task-managing-relationships.html#changing-the-settings-for-a-sync-relationship["동기화 관계의 설정을 변경하는 방법에 대해 알아봅니다"].



=== 대상에서 항목을 삭제하면 어떻게 됩니까? 소스에서도 제거됩니까?

대상에서 삭제된 항목은 원본에서 제거되지 않습니다. 관계는 소스에서 타겟으로 한 방향입니다. 다음 동기화 주기에서 Cloud Sync는 소스를 타겟과 비교하여 항목이 누락되었음을 확인하고 Cloud Sync 소스에서 타겟으로 다시 복사합니다.



== 문제 해결

https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Cloud_Sync/Cloud_Sync_FAQ:_Support_and_Troubleshooting["NetApp 기술 자료: Cloud Sync FAQ: 지원 및 문제 해결"^]



== 데이터 브로커 딥 다이브

다음 질문은 데이터 브로커와 관련이 있습니다.



=== 데이터 브로커의 아키텍처를 설명해 줄 수 있습니까?

물론입니다. 다음은 가장 중요한 사항입니다.

* 데이터 브로커는 Linux 호스트에서 실행되는 node.js 애플리케이션입니다.
* Cloud Sync는 다음과 같이 데이터 브로커를 배포합니다.
+
** AWS: AWS CloudFormation 템플릿에서
** Azure: Azure Resource Manager에서
** Google: Google Cloud Deployment Manager에서
** 고유한 Linux 호스트를 사용하는 경우 소프트웨어를 수동으로 설치해야 합니다


* 데이터 브로커 소프트웨어는 자동으로 최신 버전으로 업그레이드합니다.
* 데이터 브로커는 AWS SQS를 안정적이고 안전한 통신 채널과 제어 및 모니터링용으로 사용합니다. 또한 SQS는 지속성 계층을 제공합니다.
* 그룹에 추가 데이터 브로커를 추가하여 전송 속도를 높이고 고가용성을 추가할 수 있습니다. 하나의 데이터 브로커가 실패하는 경우 서비스 복원력을 제공합니다.

